Document: motsognir
Title: Debian motsognir Manual
Author: <insert document author here>
Abstract: This manual describes what motsognir is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/motsognir/motsognir.sgml.gz

Format: postscript
Files: /usr/share/doc/motsognir/motsognir.ps.gz

Format: text
Files: /usr/share/doc/motsognir/motsognir.text.gz

Format: HTML
Index: /usr/share/doc/motsognir/html/index.html
Files: /usr/share/doc/motsognir/html/*.html
